### ISSUE TITLE
As customer, I want to deploy a data lake, so that I can use mytiki.com

### ISSUE THREAD

**Issue by mike-audi** [tiki/core-lake#3]
### Acceptance Criteria

- [ ] A single deployable data lake
- [ ] Deployable to any aws account
- [ ] S3 based storage
- [ ] Iceberg compatability
- [ ] Support a centralized metadata catalog in Tiki accounts

### Tasks

- [x] #1 
- [x] #4
- [x] #6 
- [x] #5
